version: "3.9"

services:
  nginx:
    build: nginx/
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wp-data:/var/www/html
    restart: always
    networks:
      - inception_net
    depends_on:
      - wp

  db:
    build: db/
    container_name: db
    env_file:
      - .env
    networks:
      - inception_net
    volumes:
      - db-data:/var/lib/mysql
    restart: always

  wp:
    build: wordpress/
    container_name: wp
    env_file:
      - .env
    networks:
      - inception_net
    volumes:
      - wp-data:/var/www/html
    depends_on:
      - db
    restart: always

networks:
  inception_net:
    name: inception_net
    driver: bridge
  
volumes:
  wp-data:
    driver: local
    name: wp-data
    driver_opts:
      type: none
      device : "/home/bastien/Desktop/inception/data/wp"
      o: bind

  db-data:
    driver: local
    name: db-data
    driver_opts:
      type: none
      device : "/home/bastien/Desktop/inception/data/db"
      o: bind


